apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: beans.coin.femtoframework.org # Obligatory field to identify the resource
spec:
  group: coin # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names: # Obligatory field to identify the resource
    plural: beans
    singular: bean
    kind: Bean
    shortNames:
      - bn
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        class:
          type: string

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.coin.femtoframework.org # Obligatory field to identify the resource
spec:
  group: coin # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names: # Obligatory field to identify the resource
    plural: configs
    singular: config
    kind: Config
    shortNames:
      - cfg
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object