apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespaces.coin.femtoframework.org # Obligatory field to identify the resource
spec:
  group: coin # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v1
      served: true
      storage: true
  scope: cluster-scoped
  names: # Obligatory field to identify the resource
    plural: namespaces
    singular: namespace
    kind: Namespace
    shortNames:
      - cns
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
          additionalProperties:
            type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.coin.femtoframework.org # Obligatory field to identify the resource
spec:
  group: coin # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names: # Obligatory field to identify the resource
    plural: components
    singular: component
    kind: Component
    shortNames:
      - comp
      - cmp
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            namespace:
              type: string
            labels:
              type: object
              properties:
                belongsTo:
                  type: array
                  items:
                    type: string
                singleton:
                  type: boolean
                enabled:
                  type: boolean
                default:
                  type: boolean
                additionalProperties:
                  type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
          additionalProperties:
            type: object


---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.coin.femtoframework.org # Obligatory field to identify the resource
spec:
  group: coin # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names: # Obligatory field to identify the resource
    plural: configs
    singular: config
    kind: Config
    shortNames:
      - cfg
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            namespace:
              type: string
            labels:
              type: object
            annotations:
              type: object
      additionalProperties:
        type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: remotecomponents.coin.femtoframework.org # Obligatory field to identify the resource
spec:
  group: coin # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names: # Obligatory field to identify the resource
    plural: remotecomponents
    singular: remotecomponent
    kind: RemoteComponent
    shortNames:
      - rmc
      - rc
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            namespace:
              type: string
            labels:
              type: object
              properties:
                belongsTo:
                  type: array
                  items:
                    type: string
                singleton:
                  type: boolean
                enabled:
                  type: boolean
                default:
                  type: boolean
                additionalProperties:
                  type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            interfaces:
              type: array
              items:
                type: string
            uri:
              type: string
          additionalProperties:
            type: object
