apiVersion: coin/v1
kind: Component
metadata:
  namespace: coin-examples
  name: helloworld
spec:
  class: org.femtoframework.coin.examples.implement.SayHelloImpl
  response: 您好！世界！

---
apiVersion: coin/v1
kind: Component
metadata:
  namespace: coin-examples
  name: metrics-sample
spec:
  class: org.femtoframework.coin.examples.metrics.MetricSampleBean

---
apiVersion: coin/v1
kind: Cron
metadata:
  namespace: coin-examples
  name: helloworld-cron
spec:
  componentName: helloworld
  componentType: action
  action: sayHello
  second: 60/10
  arguments:
    1: CronTest


