apiVersion: coin/v1
kind: Component
metadata:
  namespace: coin-metrics
  name: metrics-service
spec:
  class: org.femtoframework.coin.metrics.MetricsService
  prometheusEndpoint:
    port: 8090
    daemon: false
  meterBinders:
    - class: io.micrometer.core.instrument.binder.system.UptimeMetrics
    - class: io.micrometer.core.instrument.binder.system.ProcessorMetrics
    - class: io.micrometer.core.instrument.binder.system.FileDescriptorMetrics
    - class: io.micrometer.core.instrument.binder.jvm.JvmGcMetrics
    - class: io.micrometer.core.instrument.binder.jvm.JvmMemoryMetrics
    - class: io.micrometer.core.instrument.binder.jvm.JvmThreadMetrics
    - class: io.micrometer.core.instrument.binder.jvm.ClassLoaderMetrics
