apiVersion: coin/v1
kind: Component
metadata:
  namespace: coin-metrics
  name: metrics-service
spec:
  class: org.femtoframework.coin.metrics.MetricsService
  prometheusEndpoint:
    host: 0.0.0.0
    port: 8090
    daemon: false