apiVersion: coin/v1
kind: Component
metadata:
  namespace: coin
  name: api_server
spec:
  class: org.femtoframework.coin.api.nanohttpd.APIServer
  port: 9169
  daemon: false
  api_handler:
    class: org.femtoframework.coin.api.ext.SimpleAPIHandler
